import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  safearea: {
    flex: 1,
    backgroundColor: '#1A1A1A',
  },
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  timer: {
    color: '#00FF88',
    fontSize: 24,
    fontWeight: '600',
  },
  finishButton: {
    backgroundColor: '#00FF88',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    elevation: 3,
  },
  finishButtonText: {
    color: '#0A0A0A',
    fontWeight: '700',
    fontSize: 16,
  },
  addButtonText: {
    color: '#00FF88',
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  exerciseCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
  exerciseName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  // New styles for the WorkoutScreen
  fullWidthButton: {
    width: '90%',
    backgroundColor: '#2A2A2A',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginVertical: 8,
    borderWidth: 1,
    borderColor: '#3A3A3A',
  },
  fullWidthButtonFinish: {
    width: '90%',
    backgroundColor: '#00FF88',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginVertical: 8,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
    alignItems: 'center',
    paddingTop: 20,
  },
  deleteExerciseButton: {
    position: 'absolute',
    right: 10,
    top: 10,
    backgroundColor: '#FF3B30',
    width: 48,
    height: 48,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  deleteExerciseText: {
    color: 'white',
    fontSize: 28,
    fontWeight: 'bold',
    lineHeight: 28,
  },
  addSetButton: {
    backgroundColor: '#2A2A2A',
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#3A3A3A',
  },
  addSetButtonText: {
    color: '#00FF88',
    fontSize: 14,
    fontWeight: '600',
  },
  setHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A3A',
  },
  headerColumn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
});